---
- hosts: node1.example.com
  tasks:
  
  - name: Check if httpd installed
    yum:
      name: httpd
      state: latest

  - name: Check if httpd is running
    service:
      name: httpd
      state: started

  - name: Create file fow websever
    copy:
      dest: /var/www/html/index.html
      content: 'Welcome to my web server'

  - name: Check if firewalld exists
    yum:
      name: firewalld
      state: present

  - name: Open port 80 for httpd
    firewalld:
      service: http
      permanent: true
      state: enabled
    notify:
    - Restart firewalld

  handlers:
   - name: Restart firewalld
     service:
       name: firewalld
       state: restarted
...
