---
- hosts: nodes
  tasks:
  
  - name: Remove httpd service
    yum:
      name: httpd
      state: absent
      
  - name: Delete index.html
    file:
      path: /var/www/html/index.html
      state: absent
      
  - name: Check if firewalld exists
    yum:
      name: firewalld
      state: present
      
  - name: Close port 80
    firewalld:
      service: http
      permanent: true
      state: disabled
    notify:
    - Restart firewalld
    
  handlers: 
   - name: Restart firewalld
     service: 
       name: firewalld 
       state: restarted
...
